# Generated by Django 4.2.25 on 2025-10-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='file_path',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book_covers/default.jpg', upload_to='book_covers/'),
        ),
    ]
